### ISSUE TITLE
Building host + workers + Core Tools

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-integration-tests#1]
1. Create a pipeline at each worker repro (example below focuses on the PowerShell)

      - Build worker, skip tests, push nuget package to our internal DevOps Artifacts feed

2. Create a pipeline in the azure-function-integration-tests that checks out the Host dev branch, updates the references of the packages for the workers (created in 1), and builds the Host bits using the `build-extensions.ps1` script. 
3. Create a pipeline in the Core Tools or  azure-function-integration-tests repo to build the Core Tools
     - Update package reference in the Core Tools to use the latest created packages for the workers and Host
     - Build Core Tool v3, mark this version as ‘PreRelease`, push/copy to storage account so that this version can be access via our tooling feed
    - Push core tools to a storage account
    - run e2e tests pillung core tools generated above

**Comment by pragnagopa** [comment]
cc @madelinegordon @Francisco-Gamino 

@fabiocav  as fyi

**Comment by Francisco-Gamino** [comment]
This issue is divided into 3 work items:

* Build PowerShell worker and push nuget package to our internal DevOps Artifacts feed -- https://github.com/Azure/azure-functions-integration-tests/issues/2
* Build Host and push nuget package to our internal DevOps Artifacts feed -- https://github.com/Azure/azure-functions-integration-tests/issues/3
* Build Core Tools -- https://github.com/Azure/azure-functions-integration-tests/issues/4

**Comment by pragnagopa** [comment]
cc @mhoeger

**Comment by Francisco-Gamino** [comment]
This work has been completed.
